# Example config.toml
# Used for getting context based completions

[db_context]
# default CQL password
password = "cassandara"
# default CQL user name
user = "cassandara"
# default ip to localhost
ip = "127.0.0.1"

[smart_select]
enabled = false
table_only = true
